django_blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('post.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/post/urls.py
from django.conf.urls import url
from . import views

app_name='post'

urlpatterns = [
	url(r'^$', views.post_list, name='post_list'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_single, name='post_single'),
	url(r'^category/(?P<slug>.+)/$', views.category, name='category'),
	url(r'^search-results/$', views.search, name='search'),
]

django_blog/post/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	'''Модель статей'''
	class Meta():
		db_table = 'post'
		verbose_name = 'Статья'
		verbose_name_plural = 'Статьи'
		ordering = ['date_created']

	title = models.CharField('Заголовок', max_length=100)
	category = models.ForeignKey('Category', related_name='entries', default=1)
	text = models.TextField('Текст статьи', max_length=1500)
	image = models.ImageField('Изображение', upload_to='post/', blank=True)
	date_created = models.DateTimeField('Создан', auto_now_add=True)
	date_updated = models.DateTimeField('Обновлено', auto_now=True)
	is_moderated = models.BooleanField('Модерация', default=False)

	def __str__(self):
		return self.title

class CommentPost(models.Model):
	'''Модель комментариев'''
	class Meta():
		db_table = 'comments'
		verbose_name = 'Комментарии'
		verbose_name_plural = 'Комментарии'

	user = models.ForeignKey(User, verbose_name = 'Пользователь')
	post = models.ForeignKey(Post, verbose_name = 'Статья')
	text = models.TextField('Текст комментария')
	date_created = models.DateTimeField('Добавлен', auto_now_add=True)
	is_moderated = models.BooleanField('Модерация', default=False)

	def __str__(self):
		return self.text

class Category(models.Model):
	''' Модель категории '''
	class Meta():
		db_table = 'category'
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'

	title = models.CharField('Название', max_length=100)
	slug = models.SlugField('Slug')

	def __str__(self):
		return self.title

	





django_blog/post/forms.py
from .models import CommentPost
from django import forms

class CommentForm(forms.ModelForm):
	class Meta():
		model = CommentPost
		fields = ('text',)

django_blog/post/views.py
from django.shortcuts import render, get_object_or_404
from datetime import datetime
from .forms import CommentForm
from .models import *


def post_list(request):
	posts = Post.objects.filter(is_moderated=True, date_created__lte=datetime.now()).order_by('-date_created')
	categories = Category.objects.exclude(pk=1)

	return render(request, 'index.html', {'posts': posts, 'categories': categories})

def post_single(request, pk):
	post = get_object_or_404(Post, pk=pk)
	comment = CommentPost.objects.filter(post=post, is_moderated=True)
	categories = Category.objects.exclude(pk=1)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comm = form.save(commit=False)
			comm.user = request.user
			comm.post = post
			comm.save()
			form = CommentForm()

	else:		
		form = CommentForm()
	return render(request, "post.html", { 'post': post, 'form': form, 'comment': comment, 'categories': categories})

def category(request, slug):
	category = get_object_or_404(Category,slug=slug)
	categories = Category.objects.exclude(pk=1)
	posts = category.entries.order_by('-date_created')

	return render(request, "cat.html", {'category': category, 'categories': categories, 'posts': posts})

def search(request):
	query = request.GET.get('q') or ''
	posts = Post.objects.filter(title__icontains=query).order_by('-date_created')
	categories = Category.objects.exclude(pk=1)

	return render(request, "search-results.html", {'categories': categories, 'posts': posts, 'query': query})

django_blog/templates/cat.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">

  <title>Категории</title>
  <meta name="description" content="">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- Template Basic Images Start -->
  <meta property="og:image" content="path/to/image.jpg">
  <link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon" href="img/favicon/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="img/favicon/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="img/favicon/apple-touch-icon-114x114.png">
  
  <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">

  <!-- Custom Browsers Color Start -->
  <!-- Chrome, Firefox OS and Opera -->
  <meta name="theme-color" content="#000">
  <!-- Windows Phone -->
  <meta name="msapplication-navbutton-color" content="#000">
  <!-- iOS Safari -->
  <meta name="apple-mobile-web-app-status-bar-style" content="#000">
  <!-- Custom Browsers Color End -->

</head>

<body>

  <!-- Custom HTML -->
  <header class="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Блог</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'post:post_list' %}">Главная <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form method="get" action="/search-results/" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name="q" placeholder="Поиск" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
      </form>
      </div>
    </nav>
    <nav class="main-nav">
      <div class="main-nav__inner">
      {% for category in categories %}
        <a href="{% url 'post:category' slug=category.slug %}">{{ category.title }}</a>
      {% endfor %}
      </div>
    </nav>
  </header>
  <main class="content content--pd">
    <div class="def-container">
      <section class="postblock">
        <h2 class="postblock__heading">Публикации категории "{{ category.title }}" </h2>
        <div class="postblock__posts">
        {% for post in posts %}
          <div class="postblock__item one-post">
            <a href="{% url 'post:post_single' pk=post.pk %}" class="one-post__img">
              <div>
              {% if post.image %}
                <img src="{{post.image.url}}" alt="office">
              {% endif %}
              </div>
            </a>
            <div class="one-post__content">
              <h2 class="one-post__heading">
                <a href="{% url 'post:post_single' pk=post.pk %}">{{post.title}}</a>
              </h2>
              <h5><a href = "{% url 'post:category' slug=post.category.slug %}"> {{ post.category.title }} </a></h5>

              <p class="one-post__text">{% if post.text|length > 375  %}
              {{ post.text|slice:":372"}}...
              {% else %}
              {{post.text}}
              {% endif %}
              </p>
              <div class="one-post__bottom">
                <span class="one-post__date">{{post.date_created}}</span>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
      </section>
    </div>
  </main>
  <footer class="footer">
    <div class="footer__inner">
      <p class="footer__copy">&copy; 2017 Топильницкий Владислав</p>
    </div>
  </footer>
  
  <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="{% static '/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/js/masonry.js' %}"></script>
  <script src="{% static '/js/index.js' %}"></script>

</body>
</html>

django_blog/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">

  <title>Главная</title>
  <meta name="description" content="">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- Template Basic Images Start -->
  <meta property="og:image" content="path/to/image.jpg">
  <link rel="shortcut icon" href="/img/favicon/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon" href="/img/favicon/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/img/favicon/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/img/favicon/apple-touch-icon-114x114.png">

  <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">

  <!-- Custom Browsers Color Start -->
  <!-- Chrome, Firefox OS and Opera -->
  <meta name="theme-color" content="#000">
  <!-- Windows Phone -->
  <meta name="msapplication-navbutton-color" content="#000">
  <!-- iOS Safari -->
  <meta name="apple-mobile-web-app-status-bar-style" content="#000">
  <!-- Custom Browsers Color End -->

</head>

<body>

  <!-- Custom HTML -->
  <header class="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Блог</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'post:post_list' %}">Главная <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form method="get" action="/search-results/" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name="q" placeholder="Поиск" aria-label="Search" id="search_input">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="search_btn">Найти</button>
      </form>
      </div>
    </nav>
    <nav class="main-nav">
      <div class="main-nav__inner">
      {% for category in categories %}
        <a href="{% url 'post:category' slug=category.slug %}">{{ category.title }}</a>
      {% endfor %}
      </div>
    </nav>
  </header>
  <main class="content">
    <section class="heroblock" style="background-image: url({% static '/img/hero.jpg' %})">
      <div class="heroblock__inner">
        <h1 class="heroblock__heading">Блог</h1>
        <h2 class="heroblock__subtitle">Топильницкого Владислава</h2>
      </div>
    </section>
    <div class="def-container">
      <section class="postblock">
        <h2 class="postblock__heading">Новые публикации</h2>
        <div class="postblock__posts">
        {% for post in posts %}
          <div class="postblock__item one-post">
            <a href="{% url 'post:post_single' pk=post.pk %}" class="one-post__img">
              <div>
              {% if post.image %}
                <img src="{{ post.image.url }}" alt="office">
              {% endif %}
              </div>
            </a>
            <div class="one-post__content">
              <h2 class="one-post__heading">
                <a href="{% url 'post:post_single' pk=post.pk %}">{{post.title}}</a>
              </h2>
              <h5><a href = "{% url 'post:category' slug=post.category.slug %}"> {{ post.category.title }} </a></h5>

              <p class="one-post__text">{% if post.text|length > 375  %}
              {{ post.text|slice:":372"}}...
              {% else %}
              {{post.text}}
              {% endif %}
              </p>
              <div class="one-post__bottom">
                <span class="one-post__date">{{post.date_created}}</span>
              </div>
            </div>
          </div>
        {% endfor %}


        </div>
      </section>
    </div>
  </main>
  <footer class="footer">
    <div class="footer__inner">
      <p class="footer__copy">&copy; 2017 Топильницкий Владислав</p>
    </div>
  </footer>
  
  <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="{% static '/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/js/masonry.js' %}"></script>
  <script src="{% static '/js/index.js' %}"></script>

</body>
</html>

django_blog/templates/post.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">

  <title>{{ post.title }} </title>
  <meta name="description" content="">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- Template Basic Images Start -->
  <meta property="og:image" content="path/to/image.jpg">
  <link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon" href="img/favicon/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="img/favicon/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="img/favicon/apple-touch-icon-114x114.png">
  
  <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">

  <!-- Custom Browsers Color Start -->
  <!-- Chrome, Firefox OS and Opera -->
  <meta name="theme-color" content="#000">
  <!-- Windows Phone -->
  <meta name="msapplication-navbutton-color" content="#000">
  <!-- iOS Safari -->
  <meta name="apple-mobile-web-app-status-bar-style" content="#000">
  <!-- Custom Browsers Color End -->

</head>

<body>

  <!-- Custom HTML -->
  <header class="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Блог</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'post:post_list' %}">Главная <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form method="get" action="/search-results/" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name = "q" placeholder="Поиск" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
      </form>
      </div>
    </nav>
    <nav class="main-nav">
      <div class="main-nav__inner">
      {% for category in categories %}
        <a href="{% url 'post:category' slug=category.slug %}">{{ category.title }}</a>
      {% endfor %}
      </div>
    </nav>
  </header>
  <main class="content">
    <section class="heroblock" style="background-image: url({% static '/img/hero.jpg' %})">
      <div class="heroblock__inner">
        <h1 class="heroblock__heading">{{ post.title }}</h1>
        <span class="heroblock__date">{{ post.date_created }}</span>
      </div>
    </section>
    <div class="def-container">
      <div class="def-text-block">
        <h2>{{ post.title }}</h2>
        {% if post.image %}
          <img src="{{ post.image.url }}" alt="img">
        {% endif %}
        <br>
        {{ post.text }}
        <br>
        <br>
        <h4>Комментарии</h4>
        {% for comm in comment %}
          {{comm.user}} <br>
          {{comm.text}} <br><br>
        {%endfor%}
        {% if user.is_active %}
        <p>
          <form action="" method="post">
            {%csrf_token%}
            {{form}}
            <br><input type="submit" value="Отправить">
          </form>
        </p>
        {% else %}
        <p> Чтобы оставить комментарий, войдите на сайт <p>
        {% endif %}
        <a href="{% url 'post:post_list' %}" class="btn btn-primary">На главную</a>
        <br><br>
      </div>
    </div>
  </main>
  <footer class="footer">
    <div class="footer__inner">
      <p class="footer__copy">&copy; 2017 Топильницкий Владислав</p>
    </div>
  </footer>
  
  <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="{% static '/js/bootstrap.min.js' %}"></script>

</body>
</html>

django_blog/templates/post/post_list.html
{% for post in posts %}
{{post.create}}<br />
	<a href="{% url 'post_single' pk=post.id %}">{{post.title}}</a><br />
{% if post.image %}
	<img src="{{MEDIA_URL}}{{post.image.url}}" style="width: 300px; height: 300px;" /><br/>
{% endif %}
	{{post.text}}<hr />
{% endfor %}

django_blog/templates/post_list.html
{% load static %}
{% for post in posts %}
{{post.create}}<br />
	<a href="{% url 'post:post_single' pk=post.id %}">{{post.title}}</a><br />
{% if post.image %}
	<img src="{{post.image.url}}" style="width: 300px; height: 300px;" /><br/>
{% endif %}
	{{post.text}}<hr />
{% endfor %}

django_blog/templates/post_single.html
{{post.date_created}}<br />
{{post.title}}<br />
{% if post.image %}
	<img src="{{MEDIA_URL}}{{post.image.url}}" style="width: 300px; height: 300px;" /><br/>
{% endif %}
{{post.text}}<br />
Обновлено {{post.update}} <hr><br />
<h4>Комментарии</h4>
{% for comm in comment %}
{{comm.user}} <br>
{{comm.text}} <br><br>
{%endfor%}
{% if user.is_active %}
<p>
	<form action="" method="post">
		{%csrf_token%}
		{{form}}
		<input type="submit" value="Отправить">
	</form>
</p>
{% else %}
<p> Чтобы оставить комментарий, войдите на сайт <p>
{% endif %}

django_blog/templates/search-results.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">

  <title>Результаты поиска</title>
  <meta name="description" content="">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- Template Basic Images Start -->
  <meta property="og:image" content="path/to/image.jpg">
  <link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon" href="img/favicon/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="img/favicon/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="img/favicon/apple-touch-icon-114x114.png">
  
  <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">

  <!-- Custom Browsers Color Start -->
  <!-- Chrome, Firefox OS and Opera -->
  <meta name="theme-color" content="#000">
  <!-- Windows Phone -->
  <meta name="msapplication-navbutton-color" content="#000">
  <!-- iOS Safari -->
  <meta name="apple-mobile-web-app-status-bar-style" content="#000">
  <!-- Custom Browsers Color End -->

</head>

<body>

  <!-- Custom HTML -->
  <header class="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Блог</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'post:post_list' %}">Главная <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form method="get" action="/search-results/" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name = "q" placeholder="Поиск" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
      </form>
      </div>
    </nav>
    <nav class="main-nav">
      <div class="main-nav__inner">
      {% for category in categories %}
        <a href="{% url 'post:category' slug=category.slug %}">{{ category.title }}</a>
      {% endfor %}
      </div>
    </nav>
  </header>
  <main class="content content--pd">
    <div class="def-container">
      <h2 class="search-res-heading">Результаты поиска по запросу: <span>{{ query }}</span></h2>
      <div class="search-res">
        {% for post in posts %}
        <div class="search-res__element">
          <h2><a href="{% url 'post:post_single' pk=post.pk %}">{{post.title}}</a></h2>
                  {% if post.image %}
                    <img src="{{ post.image.url }}" alt="img">
                  {% endif %}
              <h5><a href = "{% url 'post:category' slug=post.category.slug %}"> {{ post.category.title }} </a></h5>
          <p> {% if post.text|length > 100  %}
              {{ post.text|slice:":97"}}...
              {% else %}
              {{post.text}}
              {% endif %}
              <br>
              {{post.date_created}}
          </p>
        </div>
        {% endfor %}
      </div>
      <br>
    </div>
  </main>
  <footer class="footer">
    <div class="footer__inner">
      <p class="footer__copy">&copy; 2017 Топильницкий Владислав</p>
    </div>
  </footer>
  
  <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="{% static '/js/bootstrap.min.js' %}"></script>

</body>
</html>